#
# Workflow to build the website and deploy to gh-pages
#
name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history so that Hugo .GitInfo and .Lastmod work

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Test Cache
      - name: Cache conda pkgs
        uses: actions/cache@v2
        env:
          cache-name: cache-conda-pkgs
        with:
          path: |
            /usr/share/miniconda/
          key: ${{ runner.os }}-deploy-${{ env.cache-name }}-condapkgs
          #restore-keys: |
          #  ${{ runner.os }}-build-${{ env.cache-name }}-

      # Install conda
      - name: Set up conda
        uses: s-weigand/setup-conda@v1
        with:
          activate-conda: false
      - run: |
          conda --version
          which python

      # Install dependencies
      - name: Install dependencies
        run: |
          # Install Python dependencies
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Install SourceCodePro fonts
          sudo git clone --branch release --depth 1 'https://github.com/adobe-fonts/source-code-pro.git' /usr/share/fonts/opentype
          fc-cache -f -v
          # Install GMT
          conda install gmt -c conda-forge
          gmt --version
          ls /usr/share/miniconda/

      - name: Build sphinx document
        run: |
          make html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/html
